### ISSUE TITLE
EULA agreement cannot be asked

### ISSUE THREAD

**Issue by ghost** [microsoft/Azure-Kinect-Sensor-SDK#1660]
**Describe the bug**

When trying to install `libk4abt1.1-dev` in Github Actions (`ubuntu-18.04` image, with the purpose of Cloud build), the installation fails with the following error message:

```txt
Preparing to unpack .../libk4abt1.1_1.1.0_amd64.deb ...

eula agree question could not be asked
libk4abt1.1 will not be installed

dpkg: error processing archive /var/cache/apt/archives/libk4abt1.1_1.1.0_amd64.deb (--unpack):
 new libk4abt1.1 package pre-installation script subprocess returned error exit status 2
Selecting previously unselected package libk4abt1.1-dev.
Preparing to unpack .../libk4abt1.1-dev_1.1.0_amd64.deb ...
Unpacking libk4abt1.1-dev (1.1.0) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libk4abt1.1_1.1.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Installation of `k4a-tools` and `libk4a1.4-dev`, on the other hand, works just fine.

**To Reproduce**

1. Create clean repo on Github (or use existing)
2. Create Github Actions Workflow:
```yml
name: Install via Apt

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common wget curl
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo add-apt-repository -y https://packages.microsoft.com/ubuntu/18.04/prod
        sudo apt-get update
        sudo apt-get install libk4abt1.1-dev
```
3. `eula agree question could not be asked, libk4abt1.1 will not be installed`

**Expected behavior**

On every push / workflow run, `libk4abt1.1-dev` is successfully installed.

**Logs**

```txt
Preparing to unpack .../libk4abt1.1_1.1.0_amd64.deb ...

eula agree question could not be asked
libk4abt1.1 will not be installed

dpkg: error processing archive /var/cache/apt/archives/libk4abt1.1_1.1.0_amd64.deb (--unpack):
 new libk4abt1.1 package pre-installation script subprocess returned error exit status 2
Selecting previously unselected package libk4abt1.1-dev.
Preparing to unpack .../libk4abt1.1-dev_1.1.0_amd64.deb ...
Unpacking libk4abt1.1-dev (1.1.0) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libk4abt1.1_1.1.0_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS with Version: Ubuntu 18.04
 - SDK Version: 1.4.0 (also reproed on other versions) 
 - Firmware version: N/A 

**Additional context**

Github Actions Cloud Build
